In [1]:
import numpy as np

## DataTypes & Attributes

In [7]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [8]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a3 = np.array([[1, 2, 3],
               [4, 5, 6],
              [7, 8, 9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [16]:
a1

array([1, 2, 3])

In [17]:
a1.shape

(3,)

In [18]:
a2.shape

(2, 3)

In [19]:
a3.shape

(3, 2, 3)

In [22]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [23]:
a1.dtype

dtype('int32')

In [24]:
a1.size

3

In [25]:
a2.size

6

In [26]:
type(a1)

numpy.ndarray