In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3 = np.array([[1, 2, 3],
               [4, 5, 6],
              [7, 8, 9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1

array([1, 2, 3])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(3, 2, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype

dtype('int32')

In [13]:
a1.size

3

In [14]:
a2.size

6

In [15]:
type(a1)

numpy.ndarray

## Creating numpy arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int32')

In [20]:
ones = np.ones()
ones

array([1., 1., 1.])

In [21]:
ones.dtype

dtype('float64')

In [27]:
ones = np.ones(3, dtype=int)
ones

array([1, 1, 1])

In [41]:
type(ones)

numpy.ndarray

In [44]:
zeros = np.zeros((2,3), dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
range_array = np.arange(0,10,2)
range_array


array([0, 2, 4, 6, 8])

In [51]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[6, 6, 1, 5, 1],
       [8, 1, 7, 5, 4],
       [4, 4, 2, 2, 2]])

In [52]:
random_array.size

15

In [53]:
random_array.shape

(3, 5)

In [54]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.25266602, 0.17283429, 0.55104385],
       [0.49803326, 0.73751969, 0.59672059],
       [0.20414905, 0.59324966, 0.45032338],
       [0.16209456, 0.97162556, 0.30923582],
       [0.9597152 , 0.38217476, 0.45336804]])

In [70]:
random_array_3 = np.random.rand(5, 3)
random_array_3 

array([[0.32094127, 0.55879818, 0.66529827],
       [0.83675447, 0.58777315, 0.90158236],
       [0.86963991, 0.57389286, 0.42618374],
       [0.99963944, 0.17456873, 0.40586729],
       [0.31178153, 0.71471297, 0.18716169]])

### pseudo-random numbers (np.random.seed(seed=x))


In [92]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [74]:
random_array_4.shape

(5, 3)

## Viewing arrays and matrices

In [94]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [102]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [105]:
a4[:,:,:,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

In [106]:
a4[:,:,:,:2]

array([[[[6, 7],
         [5, 9],
         [3, 0],
         [2, 3]],

        [[3, 3],
         [9, 9],
         [3, 2],
         [0, 4]],

        [[8, 4],
         [8, 1],
         [9, 3],
         [0, 3]]],


       [[[4, 6],
         [4, 4],
         [7, 5],
         [5, 9]],

        [[0, 1],
         [0, 3],
         [5, 9],
         [2, 9]],

        [[2, 3],
         [9, 1],
         [2, 3],
         [0, 6]]]])

## 4. Manipulating & comparing arrays

In [108]:
a1


array([1, 2, 3])

In [109]:
ones = np.ones(3)

In [110]:
a1 + ones

array([2., 3., 4.])

In [111]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [115]:
massive_array[:10]


array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

In [118]:
%timeit sum(massive_array) #Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

#toujours utiliser numpy pour les calculs (beaucoup plus rapide)

9.43 ms ± 166 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
31.6 μs ± 1.25 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [123]:
a2, np.mean(a2), np.max(a2), np.min(a2), np.std(a2), np.var(a2)
# Variance = measure of the average degree to wich each number is different to the mean
# High variance = wider range of numbers

# Standard deviation = a measure of how spread out a group of numbers is from the mean

(array([[1, 2, 3],
        [4, 5, 6]]),
 3.5,
 6,
 1,
 1.707825127659933,
 2.9166666666666665)

In [124]:
np.sqrt(np.var(a2))

1.707825127659933

In [127]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape.shape

(2, 3, 1)

In [128]:
a2_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [131]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Dot product

In [136]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))


In [137]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [138]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [139]:
mat1 * mat2 

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [141]:
mat2_transpose = mat2.T
mat2_transpose

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [149]:
mat1.dot(mat2_transpose)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [163]:
mat1.dot(mat2.reshape(3,5))

array([[ 39,  35,  44,  55,   5],
       [ 80,  84, 104, 132,  31],
       [ 49,  66,  67,  79,  23],
       [ 77,  91, 102, 125,  32],
       [ 91, 128, 123, 141,  40]])

In [164]:
mat2.reshape(3,5)

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0]])

In [165]:
mat2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [167]:
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [170]:
import pandas as pd

In [172]:
#Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amount, index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [173]:
# Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [175]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [180]:
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [186]:
# Create daily_sales  
butter_prices.shape, weekly_sales.shape


((1, 3), (5, 3))

In [187]:
weekly_sales.T.shape

(3, 5)

In [189]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [190]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

In [191]:
a1 > a2 

array([[False, False, False],
       [False, False, False]])

In [192]:
a1 == a2


array([[ True,  True,  True],
       [False, False, False]])

In [194]:
random_array = np.random.randint(10, size=(3,5))
random_array


array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [195]:
random_array.shape

(3, 5)

In [196]:
np.sort(random_array)

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 9, 9],
       [0, 2, 3, 4, 7]])

In [198]:
np.argsort(random_array)

array([[1, 2, 3, 4, 0],
       [1, 2, 0, 3, 4],
       [0, 4, 3, 1, 2]], dtype=int64)

In [199]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [200]:
np.argmin(a1)

0

In [201]:
np.argmax(a1)


2

In [204]:
np.argmax(random_array, axis=1), np.argmax(random_array, axis=0)

(array([0, 3, 2], dtype=int64), array([0, 2, 2, 1, 1], dtype=int64))

In [283]:
# Turn an image into a NumPy array
from matplotlib.image import imread
panda = imread("images/panda.png")
print(type(panda))

panda.shape, panda.size, panda.ndim

<class 'numpy.ndarray'>


((2330, 3500, 3), 24465000, 3)

In [282]:
car = imread("images/car-photo.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [285]:
dog = imread("images/dog-photo.png")
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274